# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - uniekglas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: bcmath, gd, intl, mbstring, pdo_mysql, soap, xsl, zip, redis

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'
      - name: Configure Composer auth
        run: |
          composer config --global http-basic.repo.magento.com \
            ${{ secrets.MAGENTO_PUBLIC_KEY }} ${{ secrets.MAGENTO_PRIVATE_KEY }}
          composer config --global http-basic.hyva-themes.repo.packagist.com \
            ${{ secrets.HYVA_PUBLIC_KEY }} ${{ secrets.HYVA_PRIVATE_KEY }}
          composer config --global http-basic.composer.aitoc.com \
            ${{ secrets.AITOC_PUBLIC_KEY }} ${{ secrets.AITOC_PRIVATE_KEY }}
          composer config --global http-basic.composer.amasty.com \
            ${{ secrets.AMASTY_PUBLIC_KEY }} ${{ secrets.AMASTY_PRIVATE_KEY }}
          composer config --global http-basic.composer.bsscommerce.com \
            ${{ secrets.BSSCOMMERCE_PUBLIC_KEY }} ${{ secrets.BSSCOMMERCE_PRIVATE_KEY }}
          composer config --global http-basic.repo.webkul.com \
            ${{ secrets.WEBKUL_PUBLIC_KEY }} ${{ secrets.WEBKUL_PRIVATE_KEY }}
          composer config --global http-basic.magefan.com \
            ${{ secrets.MAGEFAN_PUBLIC_KEY }} ${{ secrets.MAGEFAN_PRIVATE_KEY }}
          composer config --global github-oauth.github.com \
            ${{ secrets.SANDER_PRIVATE_KEY }}


      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --no-dev --prefer-dist --no-progress --optimize-autoloader

      - name: Compile DI
        run: php bin/magento setup:di:compile

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_61163CA4BD6F4B669CBC327DBF2C20DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CFDCC3A5A1F84AE0B8105306E420189C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A7A2A116531442858D1688118E27873C }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'uniekglas'
          slot-name: 'uniekglas'
          package: .
          
